// This file was generated by Dashcode from Apple Inc.
// DO NOT EDIT - This file is maintained automatically by Dashcode.
function setupParts() {
    if (setupParts.called) return;
    setupParts.called = true;
    CreateInfoButton('info', { frontID: 'front', foregroundStyle: 'white', backgroundStyle: 'black', onclick: 'showBack' });
    CreateGlassButton('done', { text: 'Done', onclick: 'showFront' });
    CreateText('score', { text: 'Have Fun!' });
    CreateText('biginfo', { text: 'Game Over' });
    CreateText('up', { text: unescape('%u2B06') });
    CreateText('down', { text: unescape('%u2B07') });
    CreateGlassButton('glassbutton', { onclick: 'gotoSite', text: 'Website' });
    CreateText('userDesc', { text: 'User:' });
    CreateText('passDesc', { text: 'Pass:' });
    CreateButton('play', { text: 'Play', onclick: 'playGame', rightImageWidth: 5, leftImageWidth: 5 });
    CreateText('out', {  });
}
window.addEventListener('load', setupParts, false);
