.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH AKC 6 "SEPTEMBER 2009" ArrowKeyControl "User Manuals"
.SH NAME
akc \- ArrowKeyControl
.SH SYNOPSIS
.B akc
.SH DESCRIPTION
.B ArrowKeyControl
is a reaction testing game that tests your speed and concentration.
ArrowKeyControl does this by displaying an arrow; the arrow corresponds
to one of the arrow keys on the keyboard. You have to type arrow
displayed (which could be the up, down, left, or right arrow keys). As
soon as you type a key, the arrow changes (sometimes to the same arrow
as before!) and you go again. You have 1 second to hit the first key,
and every time you hit a key, the time allowed to ht the next key decreases.
The game continues like this as long as you press each key fast enough;
too slow and the game ends. The faster you type the correct keys, the
more you score; enter a wrong key and the game ends.

The game waits 1 second after being started to show the first arrow; this
is to give you time to prepare and move your hand to the arrow keys.

.SH BUGS
The game uses vt100 terminal commands and may not work on a vt100 incompatible terminal.
An Unicode (UTF-8) supporting terminal is required, and the game requires valid glyphs
for the triangle arrows in your terminal font to work.
.SH AUTHOR
Brenton Fletcher <i@bloople.net>

